export enum PageRoutes {
    HOME = '/',
    DASHBOARD = '/dashboard',
    REGISTER = '/register',
    LOGIN = '/login',
    FUEL = '/fuel',
    CHANGE_PASSWORD = '/change-password',
    CAR_DETAILS = '/car-details/:id',
    CAR_WASH = '/car-wash',
    CAR_SERVICES = '/car-services',
    CITY_INFO = '/city-info/:id',
    ADD_CAR = '/add-car',
    ADD_MODEL = '/add-model',
    ADD_BRAND = '/add-brand',
    ADMIN_DASHBOARD = '/admin-dashboard',
    ADMIN_BRANDS = '/admin-brands/:id',
    ADMIN_MODELS = '/admin-models/:id',
    ADMIN_CAR_SERVICES = '/admin-car-services/:id',
    ADMIN_CAR_WASH_SERVICES = '/admin-car-wash-services/:id',
    ADMIN_CITIES = '/admin-cities/:id',
    ADMIN_FUEL = '/admin-fuels/:id',
    ADMIN_GAS_STATION = '/admin-gas-stations/:id',
    PAGE_NOT_FOUND = "*"
}
